---
language: python

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - openssl aes-256-cbc -K $encrypted_7161553f13bb_key -iv $encrypted_7161553f13bb_iv -in molecule/default/clouds.yml.enc -out molecule/default/clouds.yml -d

install:
  - pip install -r requirements.txt

script:
  - travis_wait 45 detox

notifications:
  irc:
    channels:
      - "irc.freenode.org#osism"
    template:
      - "%{result} %{repository_slug}: %{commit_subject} %{build_url}"
    skip_join: true
