---
sudo: required

language: python

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - docker info

install:
  - pip install -r test-requirements.txt

script:
  - tox

notifications:
  irc:
    channels:
      - "irc.freenode.org#osism"
    use_notice: true
