---
- name: Backup existing sources.lst file
  copy:
    src: /etc/apt/sources.list
    dest: /etc/apt/sources.list.osism
    remote_src: yes
  ignore_errors: yes
  become: true

- name: Remove existing source.list file
  file:
    path: /etc/apt/sources.list
    state: absent
  become: true

- name: Add repository keys
  apt_key:
    url: "{{ item }}"
    state: present
  become: true
  with_items: "{{ repository_keys }}"

# NOTE: not using apt_repository here because it requires python-apt
- name: Add repositories
  blockinfile:
    path: /etc/apt/sources.list
    block: |
      {{ item.repository }} {{ item.name }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
    create: yes
    owner: root
    group: root
    mode: 0644
  become: true
  with_items: "{{ repositories }}"

- name: Update package cache
  package:
    update_cache: yes
  become: true

- name: Upgrade all packages
  package:
    upgrade: dist
  become: true
