---
- name: Add repository keys via URLs
  apt_key:
    url: "{{ item }}"
    state: present
  become: true
  with_items: "{{ repository_keys }}"

- name: Add repository keys via keyservers
  apt_key:
    id: "{{ item.key }}"
    keyserver: "{{ item.value }}"
    state: present
  become: true
  with_dict: "{{ repository_key_ids }}"

# NOTE: Not using apt_repository here because it requires python-apt.

- name: Copy source.list file
  template:
    src: source.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: true
  notify: Force update of package cache

- name: Update package cache
  apt:
    update_cache: yes
    cache_valid_time: "{{ repository_cache_valid_time }}"
  become: true
