---
- name: Add repository keys
  apt_key:
    url: "{{ item }}"
    state: present
  become: true
  with_items: "{{ repository_keys }}"

# NOTE: not using apt_repository here because it requires python-apt
- name: Copy source.list file
  template:
    src: source.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: true

- name: Update package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true
